[build]
  command = "npm run build"  # Adjust this based on your build script
  publish = "C:\Users\GustavoBarbosaJacome\Desktop\Jaarproject\devo"         # Specify the directory containing your build artifacts
